/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifySentRouteImport } from './routes/verify-sent'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as SermonsRouteImport } from './routes/sermons'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GivingRouteImport } from './routes/giving'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminSermonsRouteImport } from './routes/admin/sermons'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminGivingRouteImport } from './routes/admin/giving'
import { Route as AdminDepartmentsRouteImport } from './routes/admin/departments'

const VerifySentRoute = VerifySentRouteImport.update({
  id: '/verify-sent',
  path: '/verify-sent',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SermonsRoute = SermonsRouteImport.update({
  id: '/sermons',
  path: '/sermons',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GivingRoute = GivingRouteImport.update({
  id: '/giving',
  path: '/giving',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSermonsRoute = AdminSermonsRouteImport.update({
  id: '/sermons',
  path: '/sermons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGivingRoute = AdminGivingRouteImport.update({
  id: '/giving',
  path: '/giving',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/departments': typeof DepartmentsRoute
  '/giving': typeof GivingRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/sermons': typeof SermonsRoute
  '/verify': typeof VerifyRoute
  '/verify-sent': typeof VerifySentRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/giving': typeof AdminGivingRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/sermons': typeof AdminSermonsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/departments': typeof DepartmentsRoute
  '/giving': typeof GivingRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/sermons': typeof SermonsRoute
  '/verify': typeof VerifyRoute
  '/verify-sent': typeof VerifySentRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/giving': typeof AdminGivingRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/sermons': typeof AdminSermonsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/departments': typeof DepartmentsRoute
  '/giving': typeof GivingRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/sermons': typeof SermonsRoute
  '/verify': typeof VerifyRoute
  '/verify-sent': typeof VerifySentRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/giving': typeof AdminGivingRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/sermons': typeof AdminSermonsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/departments'
    | '/giving'
    | '/login'
    | '/profile'
    | '/register'
    | '/sermons'
    | '/verify'
    | '/verify-sent'
    | '/admin/departments'
    | '/admin/giving'
    | '/admin/profile'
    | '/admin/sermons'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/departments'
    | '/giving'
    | '/login'
    | '/profile'
    | '/register'
    | '/sermons'
    | '/verify'
    | '/verify-sent'
    | '/admin/departments'
    | '/admin/giving'
    | '/admin/profile'
    | '/admin/sermons'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/departments'
    | '/giving'
    | '/login'
    | '/profile'
    | '/register'
    | '/sermons'
    | '/verify'
    | '/verify-sent'
    | '/admin/departments'
    | '/admin/giving'
    | '/admin/profile'
    | '/admin/sermons'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  DepartmentsRoute: typeof DepartmentsRoute
  GivingRoute: typeof GivingRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SermonsRoute: typeof SermonsRoute
  VerifyRoute: typeof VerifyRoute
  VerifySentRoute: typeof VerifySentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-sent': {
      id: '/verify-sent'
      path: '/verify-sent'
      fullPath: '/verify-sent'
      preLoaderRoute: typeof VerifySentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sermons': {
      id: '/sermons'
      path: '/sermons'
      fullPath: '/sermons'
      preLoaderRoute: typeof SermonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giving': {
      id: '/giving'
      path: '/giving'
      fullPath: '/giving'
      preLoaderRoute: typeof GivingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sermons': {
      id: '/admin/sermons'
      path: '/sermons'
      fullPath: '/admin/sermons'
      preLoaderRoute: typeof AdminSermonsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/giving': {
      id: '/admin/giving'
      path: '/giving'
      fullPath: '/admin/giving'
      preLoaderRoute: typeof AdminGivingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminGivingRoute: typeof AdminGivingRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminSermonsRoute: typeof AdminSermonsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminGivingRoute: AdminGivingRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminSermonsRoute: AdminSermonsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  DepartmentsRoute: DepartmentsRoute,
  GivingRoute: GivingRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SermonsRoute: SermonsRoute,
  VerifyRoute: VerifyRoute,
  VerifySentRoute: VerifySentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
